### ISSUE TITLE
Optimise suggestions by sending a list

### ISSUE THREAD

**Issue by 0leslaw** [JanSzyndlarewicz/Let-s-go-out#26]
Implement a 30 match suggestions which will be refilted when it gets down to 10. Has to be done with js
              
              Jak algorytm zwraca od razu całą listę potencjalnych matchy to może można by ją całą przekazywać do templata i przełączać się między nimi js-em? Bo rozumiem że tak jak jest teraz to trzeba by wywoływać algorytm od nowa żeby dostać kolejną sugestię.

_Originally posted by @Ford544 in https://github.com/JanSzyndlarewicz/Lets-go-out/pull/24#discussion_r1854338577_

**Comment by Ford544** [comment]
Done, the numbers are different but can be adjusted easily.
